# Generated by Django 4.1 on 2023-10-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "address",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Canteen",
            fields=[
                ("ct_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "ct_name",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=50),
                ),
            ],
            options={
                "db_table": "canteen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("cmt_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "cmt_star",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "cmt_content",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("cmt_image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("cmp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("cmp_name", models.CharField(max_length=50)),
                ("cmp_tel", models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                "db_table": "company",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("cus_id", models.IntegerField(primary_key=True, serialize=False)),
                ("cus_usrname", models.CharField(max_length=20)),
                ("cus_phone", models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("dish_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dish_name", models.CharField(max_length=20)),
                ("dish_price", models.FloatField()),
                (
                    "dish_deliver",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("dish_image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "dish",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("mn_id", models.IntegerField(primary_key=True, serialize=False)),
                ("mn_name", models.CharField(max_length=20)),
                ("mn_phone", models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                "db_table": "manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="order_platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ct_name", models.CharField(max_length=50)),
                ("st_name", models.CharField(max_length=50)),
                ("dish_name", models.CharField(max_length=20)),
                ("dish_price", models.FloatField()),
                (
                    "dish_deliver",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("dish_image", models.TextField(blank=True, null=True)),
                ("st_tel", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
            options={
                "db_table": "order_platform",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("od_id", models.IntegerField(primary_key=True, serialize=False)),
                ("od_time", models.DateTimeField()),
                ("od_money", models.FloatField()),
                ("od_state", models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("st_id", models.IntegerField(primary_key=True, serialize=False)),
                ("st_name", models.CharField(max_length=50)),
                ("st_tel", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
            options={
                "db_table": "store",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usercategory",
            fields=[
                ("usrcat_id", models.IntegerField(primary_key=True, serialize=False)),
                ("usrcat_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "usercategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "usr_acc",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("usr_state", models.DecimalField(decimal_places=0, max_digits=1)),
                ("usr_password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "user_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DishAmount",
            fields=[
                (
                    "od",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="customer.orders",
                    ),
                ),
                (
                    "oder_dish_amount",
                    models.DecimalField(decimal_places=0, max_digits=2),
                ),
            ],
            options={
                "db_table": "dish_amount",
                "managed": False,
            },
        ),
    ]
