# Generated by Django 4.1 on 2023-10-28 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"managed": True},
        ),
    ]
